# -*- coding: utf-8 -*-
"""Trabalho Final Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_sxjWF3WMeK9ovBam-DTFyIgxAF6tQI_

# Avaliação Python

Aluno: Lucas Galvão Janot (22251259)

## Carregando bibliotecas:
"""

import pandas as pd

lista = [[0,1,2,3] for i in range(2)]
print(lista)

"""## Obtenção dos dados:"""

url = "https://www.cnnbrasil.com.br/esporte/futebol/tabela-brasileirao-serie-a-2022/" #atribui a uma variavel o link dos dados

cnn = pd.read_html(url) #le a url
brasileirao = cnn[0] #selecina o primeiro dataframe da variavel cnn
brasileirao #chama o dataframe

"""## Tratamento dos dados:"""

#limpesa do nome dos times
len = brasileirao.shape[0]
len

for i in range(len): 
  nome = ((brasileirao["Classificação"][i]).split(None, 1))[1]
  nomelimpo = (((nome[::-1]).split(None,1))[1])[::-1]
  brasileirao.loc[i,'Classificação'] = nomelimpo

vetor_estado = ['SP','RS','RJ','SP','RJ','PR','MG','CE','SP','MG','RJ','SP','GO','SP','PR','MT','CE','GO','PR','RS'] #cria vetor estado
vetor_titulos = ['11','3','4','7','8','1','2','0','6','0','2','8','0','0','1','0','0','0','0','0'] # cria vetor titulo
titulo_estado = pd.DataFrame({'Estado': vetor_estado, 'Titulos': vetor_titulos}) # cria dataframe com os vetores
brasileirao = pd.concat([brasileirao,titulo_estado], axis = 1) #concatena os dataframes
brasileirao #chama o dataframe

"""##Exportando os dados

"""

brasileirao.to_excel("brasileirao.xlsx", encoding = "utf-8") #exporta os dados para arquivo excel